# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal

class Ui_MainWindow(object):
    signal = pyqtSignal()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 10, 591, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar_5 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_5.setGeometry(QtCore.QRect(400, 40, 31, 191))
        self.progressBar_5.setProperty("value", 10)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(400, 240, 61, 20))
        self.label_7.setObjectName("label_7")
        self.progressBar_6 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_6.setGeometry(QtCore.QRect(260, 40, 31, 191))
        self.progressBar_6.setProperty("value", 10)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setObjectName("progressBar_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(460, 240, 91, 20))
        self.label_8.setObjectName("label_8")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 70, 151, 41))
        self.textEdit_3.setTabChangesFocus(False)
        self.textEdit_3.setReadOnly(False)
        self.textEdit_3.setOverwriteMode(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.progressBar_7 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_7.setGeometry(QtCore.QRect(330, 40, 31, 191))
        self.progressBar_7.setProperty("value", 10)
        self.progressBar_7.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_7.setObjectName("progressBar_7")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(30, 40, 131, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(30, 130, 131, 17))
        self.label_10.setObjectName("label_10")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(30, 170, 151, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.progressBar_8 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_8.setGeometry(QtCore.QRect(480, 40, 31, 191))
        self.progressBar_8.setProperty("value", 10)
        self.progressBar_8.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_8.setObjectName("progressBar_8")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(240, 240, 81, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(330, 240, 51, 17))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.progressBar_9 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_9.setGeometry(QtCore.QRect(390, 30, 31, 191))
        self.progressBar_9.setProperty("value", 10)
        self.progressBar_9.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_9.setObjectName("progressBar_9")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(390, 230, 61, 20))
        self.label_13.setObjectName("label_13")
        self.progressBar_10 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_10.setGeometry(QtCore.QRect(250, 30, 31, 191))
        self.progressBar_10.setProperty("value", 10)
        self.progressBar_10.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_10.setObjectName("progressBar_10")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(450, 230, 91, 20))
        self.label_14.setObjectName("label_14")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_5.setGeometry(QtCore.QRect(30, 60, 151, 41))
        self.textEdit_5.setTabChangesFocus(False)
        self.textEdit_5.setReadOnly(False)
        self.textEdit_5.setOverwriteMode(False)
        self.textEdit_5.setObjectName("textEdit_5")
        self.progressBar_11 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_11.setGeometry(QtCore.QRect(320, 30, 31, 191))
        self.progressBar_11.setProperty("value", 10)
        self.progressBar_11.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_11.setObjectName("progressBar_11")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 30, 131, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 120, 131, 17))
        self.label_16.setObjectName("label_16")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_6.setGeometry(QtCore.QRect(30, 160, 151, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.progressBar_12 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_12.setGeometry(QtCore.QRect(470, 30, 31, 191))
        self.progressBar_12.setProperty("value", 10)
        self.progressBar_12.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_12.setObjectName("progressBar_12")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(230, 230, 81, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(320, 230, 51, 17))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_2, "")
        self.t2 = QtWidgets.QWidget()
        self.t2.setObjectName("t2")
        self.progressBar_13 = QtWidgets.QProgressBar(self.t2)
        self.progressBar_13.setGeometry(QtCore.QRect(400, 40, 31, 191))
        self.progressBar_13.setProperty("value", 10)
        self.progressBar_13.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_13.setObjectName("progressBar_13")
        self.label_19 = QtWidgets.QLabel(self.t2)
        self.label_19.setGeometry(QtCore.QRect(400, 240, 61, 20))
        self.label_19.setObjectName("label_19")
        self.progressBar_14 = QtWidgets.QProgressBar(self.t2)
        self.progressBar_14.setGeometry(QtCore.QRect(260, 40, 31, 191))
        self.progressBar_14.setProperty("value", 10)
        self.progressBar_14.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_14.setObjectName("progressBar_14")
        self.label_20 = QtWidgets.QLabel(self.t2)
        self.label_20.setGeometry(QtCore.QRect(460, 240, 91, 20))
        self.label_20.setObjectName("label_20")
        self.textEdit_7 = QtWidgets.QTextEdit(self.t2)
        self.textEdit_7.setGeometry(QtCore.QRect(40, 70, 151, 41))
        self.textEdit_7.setTabChangesFocus(False)
        self.textEdit_7.setReadOnly(False)
        self.textEdit_7.setOverwriteMode(False)
        self.textEdit_7.setObjectName("textEdit_7")
        self.progressBar_15 = QtWidgets.QProgressBar(self.t2)
        self.progressBar_15.setGeometry(QtCore.QRect(330, 40, 31, 191))
        self.progressBar_15.setProperty("value", 10)
        self.progressBar_15.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_15.setObjectName("progressBar_15")
        self.label_21 = QtWidgets.QLabel(self.t2)
        self.label_21.setGeometry(QtCore.QRect(40, 40, 131, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.t2)
        self.label_22.setGeometry(QtCore.QRect(40, 130, 131, 17))
        self.label_22.setObjectName("label_22")
        self.textEdit_8 = QtWidgets.QTextEdit(self.t2)
        self.textEdit_8.setGeometry(QtCore.QRect(40, 170, 151, 41))
        self.textEdit_8.setObjectName("textEdit_8")
        self.progressBar_16 = QtWidgets.QProgressBar(self.t2)
        self.progressBar_16.setGeometry(QtCore.QRect(480, 40, 31, 191))
        self.progressBar_16.setProperty("value", 10)
        self.progressBar_16.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_16.setObjectName("progressBar_16")
        self.label_23 = QtWidgets.QLabel(self.t2)
        self.label_23.setGeometry(QtCore.QRect(240, 240, 81, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.t2)
        self.label_24.setGeometry(QtCore.QRect(330, 240, 51, 17))
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.t2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.progressBar_17 = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_17.setGeometry(QtCore.QRect(400, 40, 31, 191))
        self.progressBar_17.setProperty("value", 10)
        self.progressBar_17.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_17.setObjectName("progressBar_17")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(400, 240, 61, 20))
        self.label_25.setObjectName("label_25")
        self.progressBar_18 = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_18.setGeometry(QtCore.QRect(260, 40, 31, 191))
        self.progressBar_18.setProperty("value", 10)
        self.progressBar_18.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_18.setObjectName("progressBar_18")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(460, 240, 91, 20))
        self.label_26.setObjectName("label_26")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_9.setGeometry(QtCore.QRect(40, 70, 151, 41))
        self.textEdit_9.setTabChangesFocus(False)
        self.textEdit_9.setReadOnly(False)
        self.textEdit_9.setOverwriteMode(False)
        self.textEdit_9.setObjectName("textEdit_9")
        self.progressBar_19 = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_19.setGeometry(QtCore.QRect(330, 40, 31, 191))
        self.progressBar_19.setProperty("value", 10)
        self.progressBar_19.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_19.setObjectName("progressBar_19")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(40, 40, 131, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(40, 130, 131, 17))
        self.label_28.setObjectName("label_28")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_10.setGeometry(QtCore.QRect(40, 170, 151, 41))
        self.textEdit_10.setObjectName("textEdit_10")
        self.progressBar_20 = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar_20.setGeometry(QtCore.QRect(480, 40, 31, 191))
        self.progressBar_20.setProperty("value", 10)
        self.progressBar_20.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_20.setObjectName("progressBar_20")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(240, 240, 81, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(330, 240, 51, 17))
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Slow"))
        self.label_8.setText(_translate("MainWindow", "Lane Change"))
        self.label_9.setText(_translate("MainWindow", "Linear Speed"))
        self.label_10.setText(_translate("MainWindow", "Angular Speed"))
        self.label_11.setText(_translate("MainWindow", "Accelerate"))
        self.label_12.setText(_translate("MainWindow", "Keep"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "robot1"))
        self.label_13.setText(_translate("MainWindow", "Slow"))
        self.label_14.setText(_translate("MainWindow", "Lane Change"))
        self.label_15.setText(_translate("MainWindow", "Linear Speed"))
        self.label_16.setText(_translate("MainWindow", "Angular Speed"))
        self.label_17.setText(_translate("MainWindow", "Accelerate"))
        self.label_18.setText(_translate("MainWindow", "Keep"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "robot2"))
        self.label_19.setText(_translate("MainWindow", "Slow"))
        self.label_20.setText(_translate("MainWindow", "Lane Change"))
        self.label_21.setText(_translate("MainWindow", "Linear Speed"))
        self.label_22.setText(_translate("MainWindow", "Angular Speed"))
        self.label_23.setText(_translate("MainWindow", "Accelerate"))
        self.label_24.setText(_translate("MainWindow", "Keep"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t2), _translate("MainWindow", "robot3"))
        self.label_25.setText(_translate("MainWindow", "Slow"))
        self.label_26.setText(_translate("MainWindow", "Lane Change"))
        self.label_27.setText(_translate("MainWindow", "Linear Speed"))
        self.label_28.setText(_translate("MainWindow", "Angular Speed"))
        self.label_29.setText(_translate("MainWindow", "Accelerate"))
        self.label_30.setText(_translate("MainWindow", "Keep"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "robot4"))

    def setSpeed(self,lin_speed):
        self.textEdit_7.setText(lin_speed)
